### ISSUE TITLE
Preload human genome

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/ansible-artimed#10]
Since the clinicians are probably only working with human data.

**Comment by mvdbeek** [comment]
This needs to be tested.

**Comment by mvdbeek** [comment]
Given the idea to publish an application note I think this is out of scope.
It doesn't work well, makes a big image and so on.
People will just have to do this through the admin interface for the time being (Which we can document).

**Comment by drosofff** [comment]
agree totally. I was on closing this issue
