### ISSUE TITLE
with #126 PR, FTP upload button does not show up anymore using the get data Galaxy tool

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#128]
see current running aws instance at http://52.3.245.31/ until tonight

**Comment by drosofff** [comment]
So my guess is that ftp_upload_site must be specified in plain text in galaxy.ini for this button showing up.
I did it by hand, it works.

**Comment by mvdbeek** [comment]
No, if GALAXY_CONFIG_FTP_UPLOAD_SITE is set, this will be used.
Instead I guess there is a problem sourcing the startup script.
Have you, rebooted or restarted supervisor (`service supervisor restart )` ?

**Comment by drosofff** [comment]
No, I will try it immediately (removing the plain text line in galaxy.ini)

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-04-23 18:00 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
(I also installed printenv on that environment, this will help us see the available environmental variables)

**Comment by drosofff** [comment]
supervisor service restarted. No ftp button


Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-04-23 18:03 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
yes, but we do have 
GALAXY_CONF_FTP_UPLOAD_SITE=ftp://52.3.245.31
when using printenv.
Can you post the galaxy.ini in it's current state?

**Comment by drosofff** [comment]
```
server:main]
use = egg:Paste#http
use_threadpool = True

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
prefix = 
[uwsgi]
master = True

[app:main]

; options from the role's config defaults appear here
new_file_path = /home/galaxy/galaxy/database/tmp
data_manager_config_file = /home/galaxy/galaxy/config/data_manager_conf.xml.sample
external_service_type_config_file = /home/galaxy/galaxy/config/external_service_types_conf.xml.sample
visualization_plugins_directory = config/plugins/visualizations
citation_cache_lock_dir = /home/galaxy/galaxy/database/citations/locks
tool_config_file = /home/galaxy/galaxy/config/tool_conf.xml.sample,/home/galaxy/galaxy/config/shed_tool_conf.xml
template_cache_path = /home/galaxy/galaxy/database/template_cache
whoosh_index_dir = /home/galaxy/galaxy/database/whoosh_cache
job_working_directory = /home/galaxy/galaxy/database/jobs
builds_file_path = /home/galaxy/galaxy/tool-data/shared/ucsc/builds.txt.sample
migrated_tools_config = /home/galaxy/galaxy/config/migrated_tools_conf.xml
tool_data_table_config_path = /home/galaxy/galaxy/config/tool_data_table_conf.xml.sample
citation_cache_data_dir = /home/galaxy/galaxy/database/citations/data
file_path = /home/galaxy/galaxy/database/datasets
openid_consumer_cache_path = /home/galaxy/galaxy/database/openid_consumer_cache
shed_tool_data_table_config = /home/galaxy/galaxy/config/shed_tool_data_table_conf.xml
shed_data_manager_config_file = /home/galaxy/galaxy/config/shed_data_manager_conf.xml
object_store_cache_path = /home/galaxy/galaxy/database/object_store_cache
tool_sheds_config_file = /home/galaxy/galaxy/config/tool_sheds_conf.xml.sample
datatypes_config_file = /home/galaxy/galaxy/config/datatypes_conf.xml.sample
openid_config_file = /home/galaxy/galaxy/config/openid_conf.xml.sample
integrated_tool_panel_config = /home/galaxy/galaxy/config/integrated_tool_panel.xml
ucsc_build_sites = /home/galaxy/galaxy/tool-data/shared/ucsc/ucsc_build_sites.txt.sample
paste.app_factory = galaxy.web.buildapp:app_factory

; options configured by the site admin appear here
filter-with = proxy-prefix
use_pbkdf2 = True
admin_users = admin@galaxy.org
database_connection = postgresql://galaxy:galaxy@localhost:5432/galaxy?client_encoding=utf8
tool_dependency_dir = /home/galaxy/tool_dependencies
allow_user_dataset_purge = True
nginx_upload_path = /_upload
nginx_upload_store = /tmp
ftp_upload_dir = /home/galaxy/galaxy/database/ftp
nginx_x_accel_redirect_base = /_x_accel_redirect
nginx_x_archive_files_base = /_x_accel_redirect
static_enabled = False
```

**Comment by mvdbeek** [comment]
ahhh, it has to be GALAXY_CONFIG_FTP_UPLOAD SITE!
can you change this in /etc/default/supervisor and do `service supervisor restart` ?

**Comment by drosofff** [comment]
GALAXY_CONFIG_FTP_UPLOAD_SITE with a last underscore I guess...

**Comment by mvdbeek** [comment]
yes.

**Comment by drosofff** [comment]
YESSS. it worked

**Comment by mvdbeek** [comment]
cool!

**Comment by drosofff** [comment]
Do you let met do the changes and the PR ?

**Comment by mvdbeek** [comment]
If you'd like. I already got it in a branch, but it's nice test!

**Comment by drosofff** [comment]
No it's ok. I'll see whether I would have done the same. Send the PR

**Comment by drosofff** [comment]
Everything looks fine with the PR #134 👍
