### ISSUE TITLE
last effort demanded on the PR #134 ;-)

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#136]
There is still one thing not working with #134 :

the ntasks stays at 
`<param id="nativeSpecification" from_environ="NATIVE_SPEC">--ntasks=1 --share</param>`
when restarting a new instance with a different number of cores.

If the env variable is correctly exported, my guess is that the line should be removed from the job_conf.xml file ?

**Comment by drosofff** [comment]
... or maybe the line is there but does not have precedence ?

**Comment by drosofff** [comment]
It looks likes when I use the printenv tool:
`NATIVE_SPEC=--ntasks=2 --share`
Shall I close the issue ? :-)

**Comment by mvdbeek** [comment]
> ... or maybe the line is there but does not have precedence ?

Indeed, 
```
<param id="nativeSpecification" from_environ="NATIVE_SPEC">--ntasks=1 --share</param>
```
means use the option `--ntasks=1 --share` if the environmental variables NATIVE_SPEC is not defined.

**Comment by drosofff** [comment]
👍
