### ISSUE TITLE
Dockerfile for metavisitor not yet working

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#145]
see my line note in PR #141.

It seems that there is still a conflict between the ansible playbook and the CMD `--extra-vars nginx_galaxy_location=$NGINX_GALAXY_LOCATION` in the Dockerfile

**Comment by drosofff** [comment]
follow up on myself.

Maybe there was an error during the docker build. I retested quickly the Dockerfile as is but skipping the install_tools in the RUN section. This time the docker image seems ok and the container behave as expected with the nginx location
Rebuilding a metavisitor-1.2 image to see...

**Comment by drosofff** [comment]
rebuit a Docker image, and still does not work on a previous /metavisitor prefix when running the new container on /

**Comment by mvdbeek** [comment]
Yeah, the merge on travis failed again on that f***ing docker repository key verification, so that's why you didn't get a new artbio/galaxy-kickstart-base image. I triggered travis again.

**Comment by mvdbeek** [comment]
So is this still a problem, @drosofff
