### ISSUE TITLE
galaxykickstart inventory file

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#164]
For clarity of the software, I propose to:

- create a galaxykickstart inventory file at the root of the GalaxyKickStart repo containing something like that:
```
[galaxykickstart]
localhost ansible_connection=local
## adapt with
## your.ip.target.address ansible_ssh_user="root" ansible_ssh_private_key_file="~/.ssh/yoursshkey"
```
- in group_vars, to create a galaxykickstart file, more or less similar to the docker counterpart
- in extra-files, to create a minimal directory for the welcome.html, galaxykickstart logo and a short tool_list.yml containing only data_manager admin tools

It's a bit redundant with docker, I agree, but it will help to describe the application for the note

**Comment by drosofff** [comment]
see the https://github.com/ARTbio/ansible-artimed/tree/gks and the ansible-playbook test on the IFB http://192.54.201.93/

**Comment by mvdbeek** [comment]
Good, we can close this, right?

**Comment by drosofff** [comment]
Yes indeed
