### ISSUE TITLE
Installing NGS tools still needs some fixes

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#37]
I tested the galaxy-ansible server install on the IFB cloud and it seems to work.
In contrast, the current command line stated in the readme file
https://github.com/ARTbio/ansible-artimed/blob/master/README.md#installing-galaxy-ngs-tools
does not work.

We could get it working by symlinking ln -s ../../roles/ from the artimed_extras directory. But it's a hack.
The idea, if I catch properly, is not mixing playbooks and roles, ie, not having a playbook in a role folder and vice versa

**Comment by mvdbeek** [comment]
Closing since it should be fixed now.
