### ISSUE TITLE
Galaxy ansible installation is not compliant with Amazon instances whose IP address may change

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#39]
Hi
Although I did tested this with the master branch, I think the issue will exist in the not yet merged dev branch:

On AWS, the ansible-mediated install works well. However if you shut down your instance and revive it, there is a number of errors arising from the change of the host IP, including for slurm daemon and other low level components of the artimed galaxy stuff.

It is not a terrible issue as you may associate a fixed IP to a new Amazon instance and keep it for months, but people with no experience in AWS model may be fucked the first time they use an instance of artimed.

Beyond the real issue is that - most probably - the same problem will arise is we share an ansible derived AMI (Image) ! Plus the fact that, even without understanding the details, I don't see why our ansible machines would need to know their host address: 127.0.0.1 should be enough should not it ?

**Comment by mvdbeek** [comment]
Is this still current @drosofff @fabiorjvieira ?
If not, please close the issue.

**Comment by drosofff** [comment]
I think this is still the same issue as in #52 that we just saw. Amazon specific I suppose

**Comment by mvdbeek** [comment]
@drosofff so we figured this out yesterday right? Close when okay :)

**Comment by mvdbeek** [comment]
I'm going ahead and close this, re-open if there is a re-curring problem
