### ISSUE TITLE
Documentation for artimed_tool_list.yaml

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#41]
We need a documentation that explains how to generate or adapt this file for specific purpose
https://github.com/ARTbio/ansible-artimed/blob/master/roles/artimed_extras/files/artimed_tool_list.yaml

**Comment by mvdbeek** [comment]
What is the status on this?
What documentation do we have currently?

**Comment by mvdbeek** [comment]
So we currently don't have any documentation, but the file is to be put in extra-files (by convention, it could be anywhere), and then you would reference it by setting the galaxy_tools_tool_list variable to that file (see [this] (https://github.com/ARTbio/ansible-artimed/blob/rework_vars_and_travis/group_vars/travis_bioblend) ). I am adding this to issue #48 and I will close this.
