### ISSUE TITLE
Improve a bit the read me

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#48]
in https://github.com/ARTbio/ansible-artimed/blob/master/README.md#ansible-galaxy-instance-and-ngs-tools

a short description of what will happen is lacking.
basically:
- installation of a galaxy server in a /home/galaxy/galaxy dir
- customization of the web front page
- etc..
- saying that galaxy will work with slurm, 2 job handlers
- saying that galaxy will be controlled with supervisor/ctl galaxy: group

*by the way* what is the password if any of the galaxy account created by ansible.

It will be nice to have all this kind of information without need to know how to read a playbook. After all, the galaxy server does not know how it was spin on, and potential admin do not necessarily need to know it too.
Plus, this type of information will be require in an application note.

**Comment by mvdbeek** [comment]
It would be good if we can find a way to extract comments that address a variable automatically into the README.

**Comment by mvdbeek** [comment]
So this should be the next thing to do, and I think we should have a short README.md (which only says what this playbook does, and where to find the additional information) on the first page, and the rest we should build with readthedocs and sphynx.

**Comment by mvdbeek** [comment]
One of the things is to explain where to put the tool list.

**Comment by mvdbeek** [comment]
Ongoing in PR #63

**Comment by mvdbeek** [comment]
There were plenty of improvements already, i'd say let's open issues attached to a new milestone for finishing the documentation.
