### ISSUE TITLE
Test whether a public AMI made with ansible-artimed resists to new processor and ram configuration 

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#49]
See discussion in https://github.com/ARTbio/internals/pull/12
I am not speaking of a *new* ansible driven installation. I am speaking of the case you raise a Galaxy amazon instance using ansible-artimed, then you snapshot an AMI, make it public, and propose people to redeploy is on their own, without replaying any playbook (even without knowing HOW the galaxy server was designed)

I will test this when possible

**Comment by mvdbeek** [comment]
Yes, this will work and is configured by https://github.com/galaxyproject/ansible-galaxy-extras/blob/master/templates/configure_slurm.py.j2
