### ISSUE TITLE
Add CI testing.

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/ansible-artimed#51]
I would propose to use travis CI. It appears we could both test test the playbook, and testing the underlying galaxy installation. @bgruening has done an awesome job for docker-galaxy-stable (https://github.com/bgruening/docker-galaxy-stable/blob/dev/.travis.yml).

So let's 
 - [x] test succesfull playbook execution
 - [x] test building docker-artimed images
 - [x] test that galaxy can do some basic things (FTP up, run workflows ...)
 - [x] test managing/migrating a running instance
 - [ ] ~~migrate travis testing into a role/playbook section~~
 - [ ] put travis.yml testing scripts into bash/tox scripts
 - [ ] use travis to test code snippets from the documentation
 - [ ] long tool installtions time-out with travis -> setup jenkins on IFB cloud

Showstoppers:
- [x] installation of tools takes a very long time - > trim down the amount of datamanagers. Perhaps only fasta and bowtie2/bwa ?

**Comment by bgruening** [comment]
:+1: :)

**Comment by mvdbeek** [comment]
The testing is pretty decent, of course we can always improve it as we go along, but this shouldn't block the release.
