### ISSUE TITLE
proftpd on artimed AWS is not working

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#55]
does not enable FTP over TLS. Does that mean that the playbook configure proftpd for working over TLS, which is not supported by Amazon ?
```
Statut :         	Connexion à 52.90.58.200:21...
Statut :         	Connexion établie, attente du message d'accueil...
Statut :         	Serveur non sécurisé, celui-ci ne supporte pas FTP sur TLS.
Commande :	USER metavisitor@gmail.com
Réponse :     	331 Password required for metavisitor@gmail.com
Commande :	PASS ***********
Erreur :         	Connexion interrompue par le serveur
Erreur :         	Impossible d'établir une connexion au serveur
Statut :         	Attente avant nouvel essai...
Statut :         	Connexion à 52.90.58.200:21...
Statut :         	Connexion établie, attente du message d'accueil...
Réponse :     	220 ProFTPD 1.3.5rc3 Server (Galaxy ARTiMED FTP server!) [::ffff:172.30.1.160]
Commande :	AUTH TLS
Réponse :     	500 AUTH not understood
Commande :	AUTH SSL
Réponse :     	500 AUTH not understood
Statut :         	Serveur non sécurisé, celui-ci ne supporte pas FTP sur TLS.
```

**Comment by mvdbeek** [comment]
I'll have to check that against the IFB cloud.

**Comment by mvdbeek** [comment]
OK, I broke this with PR #47, because I removed the password for the galaxy postgres user.
I'll add this back in, but ideally the user should be able to not use a password for the postgresql connection.

**Comment by mvdbeek** [comment]
OK, I see this too, even with open port 1024->1048.

**Comment by mvdbeek** [comment]
though I can put files through the commandline, but not with filezillla's standard settings :/

**Comment by mvdbeek** [comment]
OK, I have tested this on aws with PR #57, this works now on commandline and filezilla, but you'll have to open the passive port range (49152 - 65534) in your VPC security group (or open all ...).
