### ISSUE TITLE
The example given in extra-files/get_tool_yml_from_gi.py does not work

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#88]
lbcd-17:extra-files chris$ python get_tool_yml_from_gi.py -g https://mississippi.snv.jussieu.fr/ -a xxxxxxxxxxxxxxxxxxxxxxxxx -o tool_list.yml
```
Traceback (most recent call last):
  File "get_tool_yml_from_gi.py", line 275, in <module>
    skip_tool_panel_section_name=options.skip_tool_panel_name)
  File "get_tool_yml_from_gi.py", line 37, in __init__
    self.tool_panel_list = self.get_tool_panel_list_from_gi()
  File "get_tool_yml_from_gi.py", line 55, in get_tool_panel_list_from_gi
    return self.gi.tools.get_tool_panel()
AttributeError: 'ToolClient' object has no attribute 'get_tool_panel'
```

**Comment by mvdbeek** [comment]
You can use this one in the meantime:
https://github.com/ARTbio/tools-artbio/blob/master/helper_scripts/get_tool_yml_from_gi.py

**Comment by mvdbeek** [comment]
Wait, those are the same files. It does work for me ... :/
`python get_tool_yml_from_gi.py -a xxxx -g https://mississippi.snv.jussieu.fr/ -o out.yml`
Any chance you're using an old version of bioblend?
I have
```
(.venv)Marius-MBP:~ marius$ pip freeze| grep bioblend
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bioblend==0.7.0
```

**Comment by drosofff** [comment]
Yes, on my local machine, probably.
I'll check and go back to the issue

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-03-18 9:52 GMT+01:00 Marius van den Beek <notifications@github.com>:

**Comment by drosofff** [comment]
indeed...

pip freeze| grep bioblend

bioblend==0.4.3.dev0

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-03-18 10:04 GMT+01:00 Christophe Antoniewski <drosofff@gmail.com>:

**Comment by mvdbeek** [comment]
Yes, "pip install --upgrade bioblend" should do it.
I can add this to the readme. Once 16.04 is released we won't need bioblend or the admin api key anymore, since we can get all the information from <galaxy_url>/api/tools

**Comment by drosofff** [comment]
Yep, it works
