### ISSUE TITLE
Indicate the Galaxy admin login & password in the doc

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#89]
In this section at least
https://github.com/ARTbio/ansible-artimed/blob/90763cca041d95c24069d1520313fb8da93966c3/docs/getting_started.md#running-the-playbook-on-a-virtual-machine

**Comment by mvdbeek** [comment]
Done with PR #92 
This is stated here: https://artbio.github.io/ansible-artimed/faq/
