### ISSUE TITLE
Collect persistent data in common location

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/ansible-artimed#9]
Again, low priority.
Things like galaxy's config folder, the postgresql folder and the database folder should be stored
on the hosts file-system, so that re-creating the instance doesn't remove previous work.
You'd need a logic to detect whether you are at the first starrt of the instance or whether this data already exists. You can take hints from docker-galaxy-stable.

**Comment by mvdbeek** [comment]
Again, this needs testing and documentation.

**Comment by fabiorjvieira** [comment]
@mvdbeek Can we persist eggs or wheels? Do you think this is a good idea?

**Comment by mvdbeek** [comment]
Sure we can, but I think this should be in the ephemeral image, since these are bound to the version of galaxy that is running.

**Comment by mvdbeek** [comment]
OK, this is done with PR #72
