### ISSUE TITLE
Is it possible to implement artimed tool list (extra-files) from .ga workflow files ?

### ISSUE THREAD

**Issue by drosofff** [ARTbio/ansible-artimed#96]
It would help to ensure consistant development of ansible instance with tools & workflows

**Comment by mvdbeek** [comment]
Yes, we're on it. With galaxy release > 16.01 we write out the toolshed
information into the workflow on export, so that could be parsed out.

**Comment by mvdbeek** [comment]
FYI: https://github.com/galaxyproject/galaxy/pull/1636
So if that would help you in the workflow to tool_list conversion, we could cherry-pick this into the mississippi server.

**Comment by drosofff** [comment]
Can this issue be closed with https://github.com/ARTbio/ansible-artimed/blob/master/extra-files/generate_tool_list_from_ga_workflow_files.py ?

**Comment by mvdbeek** [comment]
Yes, it's OK for me.
